if: tag IS blank
git:
  depth: 1
sudo: false
language: node_js
node_js:
  - "8"
env:
  - CXX=g++-4.8

before_install:
  - rm yarn.lock
  - npm install -g lerna yarn
  - ./scripts/checkout-opticss.sh build/opticss
  - ./scripts/link-to-opticss.js --hard build/opticss

install: lerna bootstrap --registry=https://registry.npmjs.org/
